language: android
dist: trusty
jdk:
  - oraclejdk11
env:
  global:
    - TARGET_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_HOME=~/android-sdk
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
before_script:
  # Prepare pre-accepted licenses to not be promted at installation
  - yes | sdkmanager "platforms;android-31"

script:
  - chmod +x ./gradlew
  - ./gradlew test
  - ./gradlew assemblerelease

notifications:
  email: false

before_install:
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
  - openssl aes-256-cbc -K $encrypted_4c721a8ffc8b_key -iv $encrypted_4c721a8ffc8b_iv
    -in apiKey.properties.enc -out apiKey.properties -d
