package com.bcr.moviejetpackcompose.utils

const val PAGER_ONBOARD_TAG = "PAGER_ONBOARD_TAG"
const val NEXT_ONBOARD_TAG = "BUTTON_NEXT_ONBOARD_TAG"
const val EMAIL_FIELD_LOGIN_TAG = "EMAIL_FIELD_LOGIN_TAG"
const val PASSWORD_FIELD_LOGIN_TAG = "PASSWORD_FIELD_LOGIN_TAG"
const val SUBMIT_BUTTON_LOGIN_TAG = "SUBMIT_BUTTON_LOGIN_TAG"
const val DIALOG_LOADING_TAG = "DIALOG_LOADING_TAG"